run:
  timeout: 5m
  tests: true

linters:
  enable:
    - errcheck      # Check for unchecked errors
    - gosimple      # Simplify code
    - govet         # Examines Go source code and reports suspicious constructs
    - ineffassign   # Detects ineffective assignments
    - staticcheck   # Go static analysis
    - unused        # Check for unused constants, variables, functions
    - gofmt         # Check whether code was gofmt-ed
    - goimports     # Check import ordering and formatting
    - revive        # Fast, extensible, flexible, configurable linter
    - misspell      # Finds commonly misspelled English words
    - unconvert     # Remove unnecessary type conversions
    - unparam       # Reports unused function parameters
    - gocritic      # Provides diagnostics that check for bugs, performance, and style issues

linters-settings:
  revive:
    rules:
      - name: exported
        disabled: false
      - name: var-naming
        disabled: false
      - name: package-comments
        disabled: true  # Allow packages without comments for now

issues:
  exclude-use-default: false
  max-issues-per-linter: 0
  max-same-issues: 0
